platform :ios, '12.0'

target 'WinkChat' do
  use_frameworks!

  # Pods for WinkChat
  pod 'CLTypingLabel', '~> 0.4.0' 
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
